### ISSUE TITLE
`Error: Community database not found` when joining cross-domain

### ISSUE THREAD

**Issue by lmangani** [pfrazee/ctzn#15]
Amazing work here and on the streams @pfrazee

I've tried spinning up a `ctzn` server at `ctzn.glitch.me` and successfully cross-connected locally created ctzns to users and posts on `test1.ctzn.network` which is super exciting.

This might be WIP or known but joining communities on different domains doesn't seem to work yet:

![image](https://user-images.githubusercontent.com/1423657/107445424-ad9eb000-6b3c-11eb-88e2-078056ccecee.png)

Shall those be recreated in any way on the remote ctzn server? If there's anything we can do or run to help test please share. 
Access to both servers/domains was through the main ctzn domain and it worked great!

If this issue is redundant/distracting i'll close it, but accept the compliments! ;)

**Comment by pfrazee** [comment]
Not distracting, thanks for filing! It is redundant though because this is a known todo and we have an open issue already (remote community joining).

Glad it’s working on glitch though! FYI this is a “testnet” currently so expect all content to get nuked between now and beta later this month.

**Comment by lmangani** [comment]
thanks @pfrazee sorry I did not see the other issue before opening! we are testing around and intent is to try authenticate ctzn users directly into our #dWebRTC #meething hopefully! keep up the great work!
