### ISSUE TITLE
"Copy link" doesn't close when clicking post underneath

### ISSUE THREAD

**Issue by ralphtheninja** [pfrazee/ctzn#33]
![Screenshot from 2021-02-27 21-05-35](https://user-images.githubusercontent.com/308049/109398861-a6024800-793f-11eb-8724-e6973fdc1326.png)

How to reproduce:

1. Click the three dots on a post -> "Copy link" opens
2. Click the post (without clicking copy link)
3. Post window opens but "Copy link" is still visible

Using:

![Screenshot from 2021-02-27 21-08-34](https://user-images.githubusercontent.com/308049/109398926-fc6f8680-793f-11eb-90ba-3dd323e453eb.png)

**Comment by unmellow** [comment]
I would like to add that for me it doesn't close when clicking anywhere even when navigating to other pages on the site
refreshing the page does get rid of it thugh i observed this behavior on firefox and agregore browser (chromium based  disrtibuted web browser)
![image](https://user-images.githubusercontent.com/30985587/113944525-a4476200-97d2-11eb-907b-e41c61cc54ad.png)

**Comment by pfrazee** [comment]
Yeah I broke this real bad

**Comment by unmellow** [comment]
this is fixed for me on firefox

**Comment by pfrazee** [comment]
Yeah I think this is fixed
