### ISSUE TITLE
Following someone issue

### ISSUE THREAD

**Issue by knownasilya** [pfrazee/ctzn#35]
When you follow someone who followed you, it creates a new notification saying they just followed you, even though they did that a while go. Seems like that should say you just followed THEM?

![ctzn-follow](https://user-images.githubusercontent.com/34726/109519343-24aed080-7a79-11eb-8b65-74eb81ba7530.gif)

**Comment by pfrazee** [comment]
Thanks for filing! Was a known issue and should be fixed now
